### ISSUE TITLE
Проблемы с host_id

### ISSUE THREAD

**Issue by AlmZ** [express42/zabbix_lwrp#37]
Добавление нового хоста в zabbix_lwrp сделано так, что при вызове рецепта сначала добавляются атрибуты этого хоста https://github.com/express42/zabbix_lwrp/blob/master/providers/host.rb. И во время выполнения рецепта connect по fqdn ноды из zabbix_api возвращает host_id и interface_id, после пытается записать их в атрибуты соответствующей ноды: https://github.com/express42/zabbix_lwrp/blob/master/providers/connect.rb#L132. Но рецепт connect выполняется только на ноде, где установлен zabbix server, а в chef одна нода не имеет прав на изменения атрибутов другой ноды. И из-за этой особенности, при обращении к атрибуту node['zabbix']['hosts'][fqdn]['host_id'] (https://github.com/express42/zabbix_lwrp/blob/master/providers/connect.rb#L303) возвращается пустое значение, что приводит к некорректной отработке ресурса zabbix_screen.

**Comment by chromko** [comment]
Fixed in a3aa7dd6ebd614ca2960d19f21b37414ca3113c2

**Comment by AlmZ** [comment]
Коммит исправляет проблему только в случае создания скрина, в остальных случаях проблема ведь остается
