### ISSUE TITLE
Credentials sent to Chef logs

### ISSUE THREAD

**Issue by e100** [express42/zabbix_lwrp#44]
The database provider is logging credentials:
https://github.com/express42/zabbix_lwrp/blob/master/providers/database.rb#L62

In the interest of security the log entry should either be removed or sanitized

**Comment by chromko** [comment]
Thanks for your issue. There was used chef the sensitive type of resources to suppress logging of some resources execution (templates, files, executes). I  think the problem is solved, isn't it?
